version: 2
updates:
- package-ecosystem: gradle
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  reviewers:
  - josephworks
  ignore:
  - dependency-name: it.unimi.dsi:fastutil
    versions:
    - 8.4.4
    - 8.5.1
    - 8.5.2
  - dependency-name: org.junit.jupiter:junit-jupiter-api
    versions:
    - 5.7.0
  - dependency-name: net.md-5:SpecialSource
    versions:
    - 1.8.6
